DANS-KNAW/easy-deposit-api

src/test/scala/nl.knaw.dans.easy.deposit/servlets/HappyRoutesSpec.scala
=> fix for travis build: tests stumbled on time zone issues

pom.xml, src/main/scala/nl.knaw.dans.easy.deposit/DataFiles.scala, src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/DatasetXml.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/FilesXml.scala, src/test/scala/nl.knaw.dans.easy.deposit/CustomMatchers.scala, src/test/scala/nl.knaw.dans.easy.deposit/DataFilesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/DepositDirSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadataSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetXmlSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/FilesXmlSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-1547 
* replace #51 
* 
* 
=> EASY-1547 Generate files.xml from files in draft bag 

pom.xml, src/main/scala/nl.knaw.dans.easy.deposit/DataFiles.scala, src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/main/scala/nl.knaw.dans.easy.deposit/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/DataFilesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletErrorSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-1659 Implement GET file-list
* maintain the draft payload with the bag-lib
* _not yet_ maintain dataset.json with the bag-lib
* because of the previous bullet the draft bag is not yet validated at submission
=> EASY-1659 Implement GET file-list

src/test/scala/nl.knaw.dans.easy.deposit/DepositDirSpec.scala
Fixes EASY-
* have processed post-merge review comment of @rvanheest : https://github.com/DANS-KNAW/easy-deposit-api/pull/74/#discussion_r231406239 
* 
* 
=> post merge review comment on #74

src/main/scala/nl.knaw.dans.easy.deposit/DataFiles.scala, src/main/scala/nl.knaw.dans.easy.deposit/authentication/AuthenticationProvider.scala, src/main/scala/nl.knaw.dans.easy.deposit/authentication/EasyBasicAuthStrategy.scala, src/main/scala/nl.knaw.dans.easy.deposit/authentication/LdapAuthentication.scala, src/main/scala/nl.knaw.dans.easy.deposit/authentication/UserPasswordStrategy.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/DepositInfo.scala, src/main/scala/nl.knaw.dans.easy.deposit/logging/ResponseLogFormatter.scala, src/main/scala/nl.knaw.dans.easy.deposit/logging/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/authentication/AuthenticationMocker.scala, src/test/scala/nl.knaw.dans.easy.deposit/authentication/LdapAuthenticationSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/authentication/SessionSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletErrorSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/HappyRoutesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala
Fixes EASY-
* see commit messages (one tyop: read scala-dow as scala-doc)
* 
=> NO JIRA ISSUE : further clean up

docs/api/api.yml
Related to EASY-1794
* Update the specs
The specs
This updates the specs but does not modify any behavior.
=> EASY-1794 Updated POST to directory specs to forbid ZIP that overwrites files

src/main/assembly/dist/install/easy-deposit-api.service
Fixes EASY-1823
* added 143 as succesCode
=> added 143 as succesCode

pom.xml, src/main/assembly/dist/cfg/logback-service.xml
Reverts DANS-KNAW/easy-deposit-api#89
@DANS-KNAW/easy
=> Revert "EASY-1826 add a journal log appender"

src/main/assembly/dist/cfg/application.properties
NO JIRA.
* Update the style of the documentation comments in the config file.
=> NO JIRA. Amended config docs.

src/main/scala/nl.knaw.dans.easy.deposit/docs/DDM.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/SchemedXml.scala, src/test/scala/nl.knaw.dans.easy.deposit/StagedFilesTargetSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/AgreementsSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/FilesXmlSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletErrorSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DoiSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/HappyRoutesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
* build  won't fail when offline
* 
=> NO JIRA ISSSUE: more precise assume for available schema

src/main/scala/nl.knaw.dans.easy.deposit/logging/RequestLogFormatter.scala
* not call certain methods twice in a row
* 
* 
Replaces #98
=> NO JIRA ISSUE: removed calling certain methods twice in a row

src/main/scala/nl.knaw.dans.easy.deposit/docs/SchemedXml.scala, src/test/scala/nl.knaw.dans.easy.deposit/StagedFilesTargetSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/AgreementsSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/FilesXmlSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletErrorSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DoiSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/HappyRoutesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Review of #99
* move `map` inside the function definition
* rename `isAvailble` to `isAvailable`
=> Review of PR #99

src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala
* log both success and failure responses in the DepositServlet
=> log both success and failure responses in the DepositServlet

src/main/scala/nl.knaw.dans.easy.deposit/Configuration.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/HttpContext.scala, src/main/scala/nl.knaw.dans.easy.deposit/PidRequesterComponent.scala, src/test/scala/nl.knaw.dans.easy.deposit/DepositDirSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/authentication/SessionSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
fixes EASY-1985
* add a custom user-agent header to Http calls
=> EASY-1985: add custom user-agent header to Http calls

src/main/assembly/dist/cfg/application.properties, src/main/rpm/2-post-install.sh
~~Fixes EASY-~~
* create default directories during RPM install
Merge together with https://github.com/DANS-KNAW/easy-dtap/pull/293
=> create default directories during RPM install

docs/api/api.yml
NO JIRA.
* Add a constraint to the PUT file_path API in the specs.
=> No JIRA. Forbid overwriting dir with file.

src/main/scala/nl.knaw.dans.easy.deposit/authentication/LdapAuthentication.scala
=> ON JIRA ISSUE : don't log user id

README.md
Reverts DANS-KNAW/easy-deposit-api#142
=> Revert "EASY-2065: test for integration with JIRA"

pom.xml, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/StateInfo.scala, src/test/scala/nl.knaw.dans.easy.deposit/EasyDepositApiAppSpec.scala
Fixes EASY-2078
* sort deposits on state and date.created
=> EASY-2078: sort deposits on state and date.created

src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/Errors.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/authentication/AuthenticationMocker.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/AgreementsSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DoiSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-2110 agreements : restore broken tests
* restore tests broken in #150 
* 
* 
=> EASY-2110 agreements : restore broken tests

pom.xml, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/StartupValidation.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/main/scala/nl.knaw.dans.easy.deposit/package.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/DataFilesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/StagedFilesTargetSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletFixture.scala
Fixes EASY-
* 
* 
* 
https://github.com/DANS-KNAW/dans-bag-lib/pull/45
=> like easy-2039 upgrade better.files for proper atomic move

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/main/scala/nl.knaw.dans.easy.deposit/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/DataFilesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/DepositDirDatasetMetadataSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/DepositDirSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/EasyDepositApiAppSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DoiSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/NotFoundSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala
EASY-2100: add property:  bag-store.bag-name
* add property:  bag-store.bag-name
easy-specs                      | [PR#81](https://github.com/DANS-KNAW/easy-specs/pull/81)     | ..
=> EASY-2100: add property:  bag-store.bag-name

src/main/scala/nl.knaw.dans.easy.deposit/docs/DDM.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala
=> EASY-2132: add instructionsForReuse to DDM

docs/api/api.yml
Accompanies EASY-2149
* Add specs request for deposit agreement
easy-deposit-agreement-creator                      | [PR#52](https://github.com/DANS-KNAW/easy-deposit-agreement-creator/pull/52/)     | ..
=> EASY-2149: Add specs for request for deposit agreement

src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala
=> EASY-2170 continued: missed a rename in the commits

src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala
Fixes EASY-
* 
* 
* 
Deploy in the circumstances the problem was detected and retry
=> HOT-FIX : missing file rights cause "Corrupt deposit: no deposit.properties found"

README.md, docs/api/api.yml, docs/index.md, src/main/assembly/bin.xml
Fixes EASY-2400
* update documentation to be in line with other projects
* remove references to outdated files from bin.xml
=> EASY-2400 update documentation

src/main/assembly/dist/cfg/template/depositConfirmation.html, src/main/assembly/dist/cfg/template/depositConfirmation.txt
Fixes EASY-2499
* add a 'kind regards' footer to email template
=> EASY-2499: Add 'kind regards' footer to email template

src/main/scala/nl.knaw.dans.easy.deposit/AgreementGenerator.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/Errors.scala, src/main/scala/nl.knaw.dans.easy.deposit/PidRequester.scala, src/main/scala/nl.knaw.dans.easy.deposit/StagedFilesTarget.scala, src/main/scala/nl.knaw.dans.easy.deposit/StateManager.scala, src/main/scala/nl.knaw.dans.easy.deposit/SubmitJob.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/main/scala/nl.knaw.dans.easy.deposit/authentication/AuthenticationSupport.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/StagedFilesTargetSpec.scala
Just more logging... nothing to see here 😉 
=> add more and better logging

src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/SubmitJob.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala
Fixes EASY-2671
* remove staged directory on error recovery
=> EASY-2671: remove staged directory on error recovery

src/main/assembly/dist/cfg/template/depositConfirmation.html, src/main/assembly/dist/cfg/template/depositConfirmation.txt
Fixes EASY-2687
* new text for deposit confirmation email
=> EASY-2687: new text for deposit confirmation email

pom.xml, src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala
fixes EASY-2179
* update parent POM version
* fix deprecation warnings
* fix scalatra breaking changes
repo                       | PR                | Note
easy-                      | [PR#](PRlink)     |
=> EASY-2179: update scalatra

src/main/assembly/dist/bin/find-UUID-pairs.sh, src/main/assembly/dist/bin/find-early-deposited-dois.sh, src/main/assembly/dist/bin/find-rejected.sh
Fixes EASY-
* have a few little scripts for trouble shooting deposits
* 
* 
=> NO JIRA ISSUE: trouble shooting tools

src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala
=> NO JIRA. Removed unit tests that used multiple titles in ddm.

src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala
NO JIRA
Resolve some failing unit tests that show up when building under Linux.
=> Fixed problems in unit test that show up when building under Linux
