DANS-KNAW/easy-deposit-api

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/test/scala/nl.knaw.dans.easy.deposit/DataFilesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/DepositDirSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadataSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetXmlSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/FilesXmlSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-1547
* allow manual test
* 
* 
Use json files in `src/test/resources/manual-test`. A deposit will fail due to a not implemented exception, but the draft bag should get the additional XML files.
=> EASY-1547 allow manual test: servlet call writeXMLs (first phase json -> ddm)

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/JsonUtil.scala, src/test/scala/nl.knaw.dans.easy.deposit/DepositDirSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletErrorSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-1464 + some more steps of EASY-1464
* add the fields that wre still missing from the deposit.properties
* add a DOI if not yet available
* check state transition before submit actions
* change the state
SubmitterSpec and a new test in IntegrationSpec illustrate the implemented changes.
Submit will fail with a not implemented exception but metadata files should be created/changed.
=> EASY-1564 deposit properties + EASY-1464 submit: doi and state

pom.xml, src/main/scala/nl.knaw.dans.easy.deposit/DataFiles.scala, src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/FilesXml.scala, src/main/scala/nl.knaw.dans.easy.deposit/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/FilesXmlSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-1464 submit
On the right hand side below `drafts` should have been `easy-ingest-flow-inbox`  
https://github.com/DANS-KNAW/easy-deposit-api/blob/1f180c26480cf05ebfa0fd61a402c2b223079dc6/src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala#L207-L209
A submit should now result in success once the metatadata is valid.
From #38 and #47 : use deasy because the local VM has no pid-generator:
1) build, deploy an create a draft deposit:
```
cd easy-deposit-api
mvn clean install
cd easy-dtap
vagrant destroy -f && vagrant up --no-provision ### only for a fresh base-box
./deploy-role.sh easy-deposit-api
curl -i -u user001:user001 -X POST http://deasy:20190/deposit
```
2) Copy the UUID returned by the curl command above. 
3) No curl command figured out to put json …
=> EASY-1464 submit

docs/api/api.yml, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/UserServlet.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/package.scala, src/test/resources/manual-test/login.html, src/test/resources/manual-test/readme.md, src/test/resources/manual-test/upload.html, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletErrorSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-1657 Implement upload single file with POST directory
* interpret the specs as sub-requests of a request with `multipart/form-data`
* `Content-Type` of the sub-requests are still ignored, so zip-files [EASY-1658](https://drivenbydata.atlassian.net/browse/EASY-1658) are uploaded as-is.
* The response code on success is 200-ok as it might be a mix of created and replaced. The specs says 201-created but that applies to subrequests. No specification how to wrap these up in the `multipart/form-data` request.
Some statistics:
* see the updated `test/resources/readme.md`
* test both PUT and POST
* test with curl: see this [stack-overflow](https://stackoverflow.com/questions/4238809/example-of-multipart-form-data)
Uploading a file of 540 MB to `deasy` resulted in the browser …
=> EASY-1657 post file using content-disposition header

src/main/scala/nl.knaw.dans.easy.deposit/servlets/AuthServlet.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala, src/test/scala/nl.knaw.dans.easy.deposit/authentication/AuthTestServlet.scala, src/test/scala/nl.knaw.dans.easy.deposit/authentication/SessionSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/HappyRoutesSpec.scala
Fixes EASY-1661
* return code for a successful login is 204 
* return code for a successful logout is 204 
Return code when deleting with invalid bag-id should be 400, but is now 404; Return code with an invalid bag-id comes from `DepositServlet`, method `getUUID`.  Simply changing the return code for this case may result in erroneous error-code in other cases => needs to be investigated
=> EASY-1661: Return 204 return code for successful login and logout calls

src/main/scala/nl.knaw.dans.easy.deposit/DataFiles.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala, src/test/scala/nl.knaw.dans.easy.deposit/DataFilesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/HappyRoutesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-1681
* return information about a file when the path in GET /deposit/{id}/file/{path} points to a file
=> EASY-1681: Return single FileInfo object for GET on specific file

docs/api/api.yml, src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadata.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/DatasetXml.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/JsonUtil.scala, src/test/resources/manual-test/datasetmetadata.json, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetXmlSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
The UI does not see that a failing submit may have assigned a DOI. Thus the next submit attempt fails because the DOI gets erased in the `metadata/dataset.json` while still present in the `deposit.properties`.
Rather than going through complex error handling and roll-back problems, the UI should go through the following steps when a user pushes the submit button:
* GET the DOI if not done by the user before
* PUT the metadata with the generated DOI
* PUT the new state
---
* The api will no longer assign a DOI on submit. In stead the api will fail if it the DOI missing.
* Copy the identifiers from json to DDM
* Give more json centric error messages on missing fields
See `src/test/resources/manual-test`
-------------------------- | …
=> NO JIRA issue: DOI bug, identifiers in DDM

docs/api/api.yml
The spec of `POST /deposit/{id}/file/{dir_path}` contained the Content-Disposition header at the message level. This was misleading, as the Content-Disposition head should be used in each message part. Corrected this and clarified the description text a bit.
See also: https://swagger.io/docs/specification/describing-request-body/file-upload#multiple
@DANS-KNAW/easy for review.
=> NO JIRA. Correct API spec.

pom.xml, src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/StagedFilesTarget.scala, src/test/scala/nl.knaw.dans.easy.deposit/DataFilesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala
Fixes EASY-1744
* move unzipped files to draft bag, not copy (again) from unzip-staging
* 
* 
=> EASY-1744 move unzipped files to draft bag, not copy (again) from unzip-staging

src/main/scala/nl.knaw.dans.easy.deposit/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/JsonUtilSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/HappyRoutesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes a part of EASY-1794
* no longer have camel case fields for FileInfo
* 
* 
=> part of EASY-1794 : no camel case for FileInfo fields

docs/api/api.yml
* Change the specs so that all concurrent POSTs are disallowed. The earlier idea to allow concurrent POSTs but to mark them as a conflict when moving the staged files, turned out to be too complex.
=> Forbid concurrent POSTs to make code simpler.

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/test/scala/nl.knaw.dans.easy.deposit/DepositDirSpec.scala
Fixes EASY-1762
* create deposits with property `identifier.dans-doi.action = create`
* 
* 
Create a deposit, examine the properties. Details:
https://github.com/DANS-KNAW/easy-deposit-api/blob/master/src/test/resources/manual-test/readme.md
https://github.com/DANS-KNAW/easy-ingest-flow/pull/87 should not be deployed before this one
=> EASY-1762 new deposit property

src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala
Fixes EASY-1815
* have unit test that don't reproduce the comment on issue 1815
* The ui should post to https://github.com/DANS-KNAW/easy-deposit-api/blob/ba07e48549881f6952b7638a01d1fdef815c125e/src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala#L215
It adds the name of the zip to the path , that creates the additional directory level.
[2018-12-03 12:43:55,149] INFO  POST http://localhost:20190/deposit/e2abf521-38d6-416f-95f9-d768fc000bfb/file/2018-03-19.zip remote=0:0:0:0:0:0:0:1; params=[]; headers=[X-Forwarded-Host -> [deasy.dans.knaw.nl], Referer -> [http://deasy.dans.knaw.nl/deposit/deposit-form/e2abf521-38d6-416f-95f9-d768fc000bfb], Origin
* 
easy- …
=> EASY-1815 additional directory levels after upload

docs/api/api.yml, src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala
Fixes
* EASY-1829 - explicit content type header when a response has a body
* EASY-1794 - #86 did not include the original objective of the issue:
When uploading/deleting files, do not return a file listing
* have changes in the swagger documentation: OK -> no-content (when updating an existing file)
* 
* 
Is the following description adequate for upload of multiple files via either a zip or multiple body parts?
https://github.com/DANS-KNAW/easy-deposit-api/blob/b962a26bdac7b26b6f1def50cff8508f5c6d54e4/docs/api/api.yml#L425-L426
=> EASY-1829 & EASY-1794 :  explicit content type & upload response codes

src/main/scala/nl.knaw.dans.easy.deposit/docs/AgreementsXml.scala
Fixes EASY-1820 : increment agreements.xsd version (rename licenseAgreement -> depositAgreement)
* 
* 
* 
deploy together with:
* https://github.com/DANS-KNAW/easy-specs/pull/63
* https://github.com/DANS-KNAW/easy-validate-dans-bag/pull/47
=> EASY-1820 : increment version of agreements.xsd due to rename

docs/api/api.yml, src/main/scala/nl.knaw.dans.easy.deposit/authentication/AuthUser.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/UserInfo.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/dm/AccessCategory.scala, src/test/resources/manual-test/datasetmetadata-from-ui-some.json, src/test/resources/manual-test/datasetmetadata.json, src/test/resources/manual-test/issue-1538.json, src/test/scala/nl.knaw.dans.easy.deposit/StagedFilesTargetSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/authentication/LdapAuthenticationSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/authentication/SessionSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/AgreementsSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadataSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/FilesXmlSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/MinimalDatasetMetadata.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletErrorSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DoiSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/HappyRoutesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-1726 drop group-access from deposit-api
* no longer provide groups in UserInfo
* only support `AccessRights.category` = REQUEST_PERMISSION / OPEN_ACCESS (as in the ui) 
* no longer accept `AccessRight.group` in dataset metadata
Try the following commands before and after deploy
curl -i -u digger001:digger001 'http://deasy.dans.knaw.nl:20190/user'
curl -i -u user001:user001 --data '{"accessRights": {"category":"OPEN_ACCESS","group": "string"  }}' -X PUT 'http://deasy.dans.knaw.nl:20190/deposit/UUID/metadata
* the first command will no longer return `"groups":["Archeology"]`
* the second command will no longer succeed
* login with the ui should still succeed ans show the usual info
-------------------------- | …
=> EASY-1726 drop group-access from deposit-api

src/main/assembly/dist/bin/easy-deposit-api
Fixes EASY-1670
* It is possible to pass parameters containing spaces
=> EASY-1670 Command-line startup script: argumenten met spaties

src/main/scala/nl.knaw.dans.easy.deposit/docs/DDM.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadata.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/dm/Author.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadataSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/ValidationSpec.scala
Fixes EASY-1747 postpone validation to submit (so far authors only)
* no longer cause validation errors on authors (creators/contributors and the rights-holders among them) when saving metadata
* postponing validation of schemed objects _inside and outside_ authors is still out of scope for this pull request
* friendly error messages are kept out of scope, see [EASY-1905](https://drivenbydata.atlassian.net/browse/EASY-1905) therefore submission relies on schema validation for now unless something would not be covered.
=> EASY-1747 postpone validation to submit (authors only)

src/main/scala/nl.knaw.dans.easy.deposit/docs/DDM.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadata.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/JsonUtil.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/dm/Date.scala, src/test/resources/logback.xml, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadataSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/MinimalDatasetMetadata.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/ValidationSpec.scala
Fixes EASY-1747 postpone validation to submit (authors only)
* no longer cause validation errors on dates when saving metadata
* friendly error messages are kept out of scope, see [EASY-1905](https://drivenbydata.atlassian.net/browse/EASY-1905) therefore submission relies on schema validation for now unless something would not be covered.
=> EASY-1747 postpone validation to submit (dates)

src/main/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadata.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/dm/Author.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/dm/Date.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/dm/Mandatory.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/dm/Spatial.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadataSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/ValidationSpec.scala
Fixes EASY-1747 postpone validation to submit (spatial points/boxes)
* no longer cause validation errors on spatial points/boxes when saving metadata
* conversion is beyond the scope of this issue, which is:
_accept partial data on save, but not on submit_
* api should apply same conversion of x/y to lat/long as bulk import, the source of this code
=> EASY-1747 postpone validation to submit (spatial points/boxes)

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala
Fixes EASY-1962 fix bag-info.txt
* dropped user-account
* added created
* 
* build and deploy on deasy
* Submit a deposit with the ui
* Work around https://drivenbydata.atlassian.net/browse/EASY-1932
`sudo chgrp -R deposits /var/opt/dans.knaw.nl/tmp/easy-ingest-flow-inbox/` 
`sudo chmod -R 755 /var/opt/dans.knaw.nl/tmp/easy-ingest-flow-inbox/` 
`sudo service easy-ingest-flow restart`
ingest-flow now only complains about `metadata/message-from-depositor.txt` but that is to be fixed with https://drivenbydata.atlassian.net/browse/EASY-1961
=> EASY-1962 fix bag-info.txt

src/main/assembly/dist/cfg/application.properties, src/main/rpm/2-post-install.sh, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/test/resources/debug-config/application.properties, src/test/scala/nl.knaw.dans.easy.deposit/StagedFilesTargetSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala
Fixes EASY-1932 file rights before moving to ingest inbox
* add group "deposits" to files
* give write access to group
* as a consequence of the above bullets, a deposit with the ui (alias PUT /deposit/{id}/state SUBMITTED) will no longer cause a warning about not writeable files
workaround in #115 would no longer be needed 
will still cause validation errors unless the other known issues are fixed
* https://github.com/DANS-KNAW/easy-dtap/pull/301 
* the draft #119 has already merge conflicts with this pull request
=> EASY-1932 file rights before moving to ingest inbox

docs/api/api.yml, src/main/scala/nl.knaw.dans.easy.deposit/docs/DDM.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadata.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/JsonUtil.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/SchemedXml.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/dm/AccessRights.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/package.scala, src/test/resources/manual-test/datasetmetadata-from-ui-all.json, src/test/resources/manual-test/datasetmetadata-from-ui-some.json, src/test/resources/manual-test/datasetmetadata.json, src/test/resources/manual-test/issue-1538.json, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadataSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/JsonUtilSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/MinimalDatasetMetadata.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DoiSpec.scala
Fixes EASY-1902 : flatten AccessRights.category
* reduce a complex json field to a simple one:
old: ` "accessRights": { "category": "OPEN_ACCESS" },`
new: `"accessRights": "OPEN_ACCESS",`
* 
*
=> EASY-1902 : flatten AccessRights.category (breaks ui and pending drafts)

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala
Fixes EASY-1962 again: fix bag-info of staged-for-submit
* get submits further down the validation by easy-ingest-flow
* on deasy there is still a problem with existing DOI's
* 
=> EASY-1962 fix bag-info of staged-for-submit (not of the draft)

src/main/scala/nl.knaw.dans.easy.deposit/docs/dm/Date.scala, src/test/resources/manual-test/issue-1538.json, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadataSpec.scala
Fixes EASY-
* be possible to specify plain dates
* 
* 
=> NO JIRA : date qualifier: dc:date -> dcterms:date

docs/api/api.yml, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala
Fixes EASY-2013 document how lat/long is mapped to x/y
* 
* 
* 
=> EASY-2013 document how lat/long is mapped to x/y

src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/NotFoundSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala
Fixes EASY-1949 + EASY-1950 checks on PUT file (no zip, no file overwriting directory)
* Fix EASY-1949 reject zip files for PUT file requests
* Fix EASY-1950 reject a file that would overwrite a directory
* 
=> EASY-1949 + EASY-1950 checks on PUT file (no zip, no file overwriting directory)

docs/api/api.yml, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-1947 PUT file with Content-Type: multipart/form-data results in corrupt upload
* fix an oversight in documentation of nested zips in #132
* document/check no multipart is PUT file request
=> EASY-1947 multipart not allowed for PUT file requests

src/main/assembly/dist/cfg/application.properties, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/package.scala, src/test/resources/debug-config/application.properties, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletErrorSpec.scala
Fixes EASY-2044 upload of large files
* read at most 3MB in memory for uploads
* 
* 
* create a big file: `head -c 1073741824 < /dev/urandom > 1GB.txt`
* try to upload it before deploy
* try to upload it after deploy
* while the progess bar is growing you will see a file growing in size:
`/var/opt/dans.knaw.nl/tmp/easy-deposit-api/multipart-location/MultiPart*`
* when the request completes (with success or not) it disppears
https://github.com/DANS-KNAW/easy-dtap/pull/319
=> EASY-2044 upload of large files

src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadataSpec.scala
Fixes EASY-1905 add more tests for DatasetMetadataSpec
* add more tests for DatasetMetadataSpec
=> EASY-1905 add more unit tests for DatasetMetadataSpec, only return the part that is invalid

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/Errors.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/test/scala/nl.knaw.dans.easy.deposit/DepositDirSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-2055 
* generate a new `bag-store.bag-id` at each (re)submit
* use this ID as directory in ingest-flow-inbox
=> EASY-2055 generate bag-store.bag-id at submit

src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-2079: Deposit api does not write message-from-depositor and agreements.xml to correct Dir
easy-stage-dataset                      | [PR#138](https://github.com/DANS-KNAW/easy-stage-dataset/pull/138)     | ..
=> EASY-2079: Deposit api does not write message-from-depositor and agreements.xml to correct Dir

src/main/assembly/dist/cfg/application.properties, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/StartupValidation.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/main/scala/nl.knaw.dans.easy.deposit/package.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/package.scala, src/test/resources/manual-test/upload.html, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletErrorSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/RichFileItemsSpec.scala
Fixes part of EASY-2068 don't store uploads twice
* store files initially as `/var/opt/dans.knaw.nl/tmp/easy-deposit-api/multipart-location/multipartSOMETHING`
* once all files are uploaded (the status bar reaches 100%)
* deposit-api logs the request
* files will be renamed within `multipart-location` and moved to `stage-zips`
* the sha will be calculated and the files moved to the draft bag
while busy for too long the ui can get a status 502
* deposit-api logs the reseponse
* uploading multiple files can be tested with `src/test/resources/manual-test/upload.html` for a single file you can use http://deasy.dans.knaw.nl/deposit
* monitor logging of deposit-api
* monitor files and space availabel with something like
```
cd /var/opt/dans.knaw.nl/tmp/easy-deposit-api/drafts/user001/d5cf201f-e7 …
```
=> EASY-2068 don't store uploads twice

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/test/scala/nl.knaw.dans.easy.deposit/DepositDirSpec.scala
Fixes EASY-2109 skip corrupt deposits
* Won't fail when one of the deposit directories is corrupt
* 
* 
* add a directory between the drafts of a user that is not a UUID,
* try to show the list of deposits
* it will no longer fail, the problematic directory is logged
=> EASY-2109 skip corrupt deposits

src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/Errors.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/AgreementsXml.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/authentication/AuthenticationMocker.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/AgreementsSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DoiSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-
* generate agreement.xml according to ne schema
* switched off some unit tests to be fixed in a next PR
* 
* build and deploy on deasy
* `sudo service easy-ingest-flow stop`
* submit a deposit with the ui
* `cat /var/opt/dans.knaw.nl/tmp/easy-ingest-flow-inbox/*/bag/metadata/depositor-info/agreements.xml`
or UUID for `*`
* `sudo service easy-ingest-flow start`
=> EASY-2110 upgrade agreements schema

docs/api/api.yml
Fixes EASY-2029
* Remove 'AlreadySubmitted' error message on POST/PUT
* Allow POST to overwrite files
=> EASY-2092: POSTs MAY overwrite existing files

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/StateInfo.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/StateInfoSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes api side of EASY-2112 : no update of rejected deposit
* require the client to change the state from REJECTED to DRAFT before updating a dataset
* checks if update is allowed for POST uploads
=> EASY-2112 : no update of rejected deposit

README.md, pom.xml, src/test/scala/nl.knaw.dans.easy.deposit/authentication/SessionSpec.scala
https://github.com/eclipse/jetty.project/issues/3683
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.19.v20190610
Fixes EASY-2152 : upgrade jetty with fix for cleanup of multipart on aborted upload
* remove multipart files of aborted uploads
* 
* 
on deasy
* `watch ls -la /var/opt/dans.knaw.nl/tmp/easy-deposit-api/multipart-location/`
* upload a large file
* abort before the status bar reaches 100%
* before deploy the multipart file is not removed, after deploy it will be removed
=> EASY-2152 : upgrade jetty with fix for cleanup of multipart on aborted upload

src/main/scala/nl.knaw.dans.easy.deposit/docs/DDM.scala, src/test/resources/manual-test/datasetmetadata-from-ui-all.json, src/test/resources/manual-test/datasetmetadata.json, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadataSpec.scala
Fixes EASY-2116: add language of files to DDM
*  add language of files to DDM
* https://github.com/DANS-KNAW/easy-ddm/pull/34
=> EASY-2116: add language of files to DDM

debug-init-env.sh, src/main/assembly/dist/cfg/application.properties, src/main/rpm/2-post-install.sh, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/Errors.scala, src/main/scala/nl.knaw.dans.easy.deposit/StateManager.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/main/scala/nl.knaw.dans.easy.deposit/authentication/AuthenticationSupport.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/AbstractAuthServlet.scala, src/test/resources/debug-config/application.properties, src/test/scala/nl.knaw.dans.easy.deposit/StateManagerSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/RichFileItemsSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala
Fixes 
EASY-2170 : locks for submits and POST/PUT uploads;
EASY-2081 : internal service error
* combines both staged directories into a single one
* implements optimistic locking also for 
* fetching `StateInfo` of a submitted deposit won't cause an internal error when properties in (or pointing to) the ingest-flow-inbox are not found (not yet or no longer). The state available in the draft area will be returned and the missing property logged.
Requirements
* this pull request deployed on deasy
* a small file and a large file (a few GB) to have some time to start a concurrent upload/submit
* the UUID of a draft dataset that is ready to receive uploads
* two browser windows with the deposit-ui ready for a POST upload (or submit with a large file in the bag)
* a curl command prepared for a …
=> EASY-2170 : locks for submits and POST/PUT uploads; EASY-2081 : internal service error

src/main/scala/nl.knaw.dans.easy.deposit/StateManager.scala, src/test/scala/nl.knaw.dans.easy.deposit/StateManagerSpec.scala
* wrap URLs in the deposit description in `<a/>` tags, so that they are clickable in `easy-deposit-ui`
* https://github.com/DANS-KNAW/easy-deposit-ui/pull/174
* https://github.com/DANS-KNAW/easy-deposit-api/pull/161/files?file-filters%5B%5D=.properties&file-filters%5B%5D=.scala#r296196986
=> wrap URL in deposit description in <a/> tag, to be rendered in easy-deposit-ui

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/StateManager.scala, src/test/scala/nl.knaw.dans.easy.deposit/DepositDirSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala
Fixes EASY-2173
* add new property `deposit.source` to deposit properties
* gives this property value `API`
easy-manage-deposit                      | [PR#54](https://github.com/DANS-KNAW/easy-manage-deposit/pull/54)     | ..
easy-sword2                      | [PR#132](https://github.com/DANS-KNAW/easy-sword2/pull/132)     | ..
easy-split-multi-deposit                      | [PR#138](https://github.com/DANS-KNAW/easy-split-multi-deposit/pull/138)     | ..
easy-specs                     | [PR#82](https://github.com/DANS-KNAW/easy-specs/pull/82)     | ..
=> EASY-2173: 'origin' kolom voor deposit report

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/Errors.scala, src/main/scala/nl.knaw.dans.easy.deposit/StateManager.scala, src/test/scala/nl.knaw.dans.easy.deposit/EasyDepositApiAppSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/StateManagerSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala
Fixes EASY-2222 overide stacktrace by ingest-flow with mail-to-dans message
* generate mailto-links with two variants of generated references:
* one with the UUID found with `bag-store.bag-id` in the `deposit.properties of the draft deposit`
* one with 'DRAFT/<user>/<UUID>' as fallback if the property (or submitted copy of the draft) was not found
The template in `StateManager.mailtoDansMssage` and when the method is called 
* `easy-dtap` and `easy-app` on ui-integration branch
* build/deploy `easy-deposit-api` and `easy-webui`
* shut down a service like `easy-validate-dans-bag `
* submit a deposit (with at least one file uploaded)
* refresh the list of deposits until ingest-flow is done
* Try the `expectedURL`-s in `StateManagerSpec`, result is shown in the screenshots. 
* The link only …
=> EASY-2222 overide stacktrace by ingest-flow with mail-to-dans message

src/main/scala/nl.knaw.dans.easy.deposit/docs/DDM.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala
Fixes EASY-2246
* swap order of fields in `<dcx-dai:organization>` to make sure the produced DDM validates according to the schema
=> EASY-2246: fix validation error in <dcx-dai:organization>

docs/api/api.yml
changes the ForbiddenUpdate description to more accurately describe the resolution of https://drivenbydata.atlassian.net/browse/EASY-2112
Fixes EASY-2272
* correctly display the description of a HTTP 409 code in Swagger UI
* fix the ForbiddenUpdate description to more accurately match the current behavior
=> EASY-2272: fix typo and fix ForbiddenUpdate description

src/main/scala/nl.knaw.dans.easy.deposit/docs/DDM.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/DatasetMetadata.scala, src/test/resources/manual-test/datasetmetadata-from-ui-all.json, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala
Fixes EASY-2205
* Map alternative identifiers to isFormatOf instead of identifier
* Use non-versioned ddm.xsd
* Add testcases
=> EASY-2205: Map alternative identifiers to isFormatOf

src/main/scala/nl.knaw.dans.easy.deposit/docs/UserInfo.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/HappyRoutesSpec.scala
Fixes EASY-2257 : new attribute "displayName" for "UserInfo"
* 
* 
* 
https://github.com/DANS-KNAW/easy-deposit-ui/pull/186 should be merged/deployed after this
=> EASY-2257 : new attribute "displayName" for "UserInfo"

src/main/assembly/dist/cfg/application.properties, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/test/resources/debug-config/application.properties, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala
Fixes EASY-2282
* add deposit-ui form url to 'message for the datamanager' during submit
See also:
* https://github.com/DANS-KNAW/easy-dtap/pull/367
=> EASY-2282: add deposit-ui form url to 'message for the datamanager' during submit

docs/api/api.yml
Fixes EASY-2262 : merge dirs with same names in different zipped uploads
* 
* 
* 
=> EASY-2262 : merge dirs with same names in different zipped uploads

src/main/assembly/dist/cfg/application.properties, src/main/scala/nl.knaw.dans.easy.deposit/AgreementGenerator.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/test/resources/debug-config/application.properties, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala
NO JIRA.
* Make it possible to configure the connection-timeout and the read-timeout of the connection to `easy-deposit-agreement-generator`.
=> NO JIRA. Make timeouts for agreement-generator connection configurable

src/main/assembly/dist/cfg/application.properties, src/main/scala/nl.knaw.dans.easy.deposit/AgreementGenerator.scala, src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/test/resources/debug-config/application.properties, src/test/scala/nl.knaw.dans.easy.deposit/AgreementGeneratorSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/DebugConfigSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala
Fixes EASY-2473: configurable agreement attachment: html or pdf
* 
* 
* 
* build and deploy together with generator.
* submit a new deposit
* when pdf is configured the KNAW delivers the message in the inbox
when html is configured the message is marked as spam
* depends on https://github.com/DANS-KNAW/easy-deposit-agreement-generator/pull/6
* most likely conflicts with #191
* possibly dtap should implement all the new entries in `application.properties`
=> EASY-2473: configurable agreement attachment: html or pdf

src/main/scala/nl.knaw.dans.easy.deposit/EasyDepositApiApp.scala, src/test/scala/nl.knaw.dans.easy.deposit/EasyDepositApiAppSpec.scala
~Fixes EASY-~
* sort deposits on state, then date.created (newest to oldest) (previously it was 'oldest to newest')
=> sort deposits on state, then date.created (newest to oldest)

src/main/assembly/dist/cfg/application.properties, src/main/assembly/dist/cfg/template/depositConfirmation.html, src/main/assembly/dist/cfg/template/depositConfirmation.txt, src/main/scala/nl.knaw.dans.easy.deposit/Mailer.scala, src/main/scala/nl.knaw.dans.easy.deposit/Submitter.scala, src/test/scala/nl.knaw.dans.easy.deposit/MailerSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/TestSupportFixture.scala
Fixes EASY-2494 confirmation email explains other attachments
* 
* 
* 
build/deploy on deasy:
The latter lacks the `files.xml` and thus has other text
=> EASY-2494 confirmation email explains other attachments

docs/api/api.yml, src/main/scala/nl.knaw.dans.easy.deposit/docs/AgreementUser.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/UserData.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/UserInfo.scala, src/main/scala/nl.knaw.dans.easy.deposit/servlets/UserServlet.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/HappyRoutesSpec.scala
Fixes EASY-2500
* restore user data that is exposed through the servlet
* update the API documentation to conform to the expected output
* fix a copy-paste error in `AgreementUser`
* fix a incorrect key for fetching the firstname (initials) from the LDAP data
These bugs were introduced in https://github.com/DANS-KNAW/easy-deposit-api/pull/189; see also the analysis in the [issue](https://drivenbydata.atlassian.net/browse/EASY-2500).
=> EASY-2500: restore user data that is exposed through the servlet

src/main/scala/nl.knaw.dans.easy.deposit/Mailer.scala, src/test/scala/nl.knaw.dans.easy.deposit/MailerSpec.scala
Fixes EASY-2512
* fix incomplete pattern match that caused mail not to be sent on empty attachment
=> EASY-2512: fix incomplete pattern match that caused mail not to be sent on empty attachment

pom.xml, src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DepositServletErrorSpec.scala
Fixes EASY-2332
* validate `UUIDs` using `dans.lib.string.toUUID` method
**Note**: In the following classes `UUID` is created directly by calling `UUID.fromString` method because these bagId-strings come from already existing bags:
* DepositDir,  StateManager
easy-archive-bag   | [PR#66](https://github.com/DANS-KNAW/easy-archive-bag/pull/66)     | ..
easy-auth-info   | [PR#36](https://github.com/DANS-KNAW/easy-auth-info/pull/36)     | ..
easy-bag-index  | [PR#50](https://github.com/DANS-KNAW/easy-bag-index/pull/50)     | ..
easy-bag-store  | [PR#100](https://github.com/DANS-KNAW/easy-bag-store/pull/100)     | ..
easy-delete-dataset  | …
=> EASY-2332: validation of UUIDs

src/main/scala/nl.knaw.dans.easy.deposit/DepositDir.scala, src/main/scala/nl.knaw.dans.easy.deposit/SubmitJob.scala, src/main/scala/nl.knaw.dans.easy.deposit/package.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitJobSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala
Fixes EASY-2548
* use draft `depositId` as the name of the bag in de submit `depositId`
=> EASY-2548: use draft depositId as the name of the bag in de submit depositId

docs/api/api.yml, src/main/scala/nl.knaw.dans.easy.deposit/DataFiles.scala, src/main/scala/nl.knaw.dans.easy.deposit/docs/FileInfo.scala, src/test/scala/nl.knaw.dans.easy.deposit/DataFilesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/JsonUtilSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/HappyRoutesSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/IntegrationSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/UploadSpec.scala
Fixes EASY-2529
* include file size in FileInfo responses
* https://github.com/DANS-KNAW/easy-deposit-ui/pull/241
=> EASY-2529: include file size in FileInfo responses

src/main/assembly/dist/bin/deposit-states.sh
Fixes EASY-
* show whether or not the API status of deposits is in sync with ingest-flow
* 
when executed on deasy it shows something like 
```
/var/opt/dans.knaw.nl/tmp/easy-deposit-api/drafts/user001/59662d4a-0933-4dc3-bb6b-7278ef723368/deposit.properties:state.label = SUBMITTED
/var/opt/dans.knaw.nl/tmp/easy-ingest-flow-inbox/7cc675af-bedc-4eb4-9a15-5f872def6434/deposit.properties:state.label = FAILED
/var/opt/dans.knaw.nl/tmp/easy-deposit-api/drafts/user001/ef67e49d-b75e-4e6b-95a9-bec46b9a069a/deposit.properties:state.label = IN_PROGRESS
/var/opt/dans.knaw.nl/tmp/easy-ingest-flow-inbox/8fef6190-af09-4f6c-ad9d-a5906a3bf60b/deposit.properties:state.label = IN_REVIEW
```
easy- …
=> NO JIRA ISSUE : another tool for maintenance / trouble shooting

src/main/scala/nl.knaw.dans.easy.deposit/docs/DDM.scala, src/main/scala/nl.knaw.dans.easy.deposit/package.scala, src/test/resources/manual-test/datasetmetadata-from-ui-all.json, src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala, src/test/scala/nl.knaw.dans.easy.deposit/docs/DDMSpec.scala
demonstrates DD-412: white space treatment
* have a new unit test that demonstrates loss of white space as saved by the depoit-ui
* 
run https://github.com/DANS-KNAW/easy-deposit-api/blob/ed02f121608d0b79d4796df1a0efd64730a89427/src/test/scala/nl.knaw.dans.easy.deposit/SubmitterSpec.scala#L187
and examine `target/test/SubmitterSpec/submitted/*/*/metadata/dataset.xml`
When debugging, all white space is still preserved in both `trimmed` and `elem` when formatting
https://github.com/DANS-KNAW/easy-deposit-api/blob/dfe23552767ae87d6081f6976d15bfbf6a9b4d5c/src/main/scala/nl.knaw.dans.easy.deposit/package.scala#L33-L35
Note that the `PrettyPrinter` is used everywhere down the chain.
easy- …
=> DD-412: white space treatment

src/main/scala/nl.knaw.dans.easy.deposit/docs/DDM.scala
…tadata
Fixes EASY-2830
* Only the `first title` will be written in DDM `profile`
* The `rest of the titles `will be written in DDM `dcmiMetadata` as alternative titles
=> EASY-2830: easy-deposit-api mag maar 1 titel in het profile zetten

src/main/scala/nl.knaw.dans.easy.deposit/servlets/DepositServlet.scala, src/test/scala/nl.knaw.dans.easy.deposit/servlets/DoiSpec.scala
Fixes EASY-2878: fix ezproxy in license URL
* 
* 
* 
* in `easy-dtap` run `start-preprovisioned-box.py -s deasy`o
* hack urls in `easy-licenses/src/main/resources/licenses/licenses.*`, build and deploy: no change visible with the browser inspector
* manual hack of the urls
=> EASY-2878 fix ezproxy in license URL
